"""Same_as_previous_just_secure

Revision ID: 5a52952ea8c5
Revises: a48381bcbf1f
Create Date: 2021-10-14 02:31:54.492194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a52952ea8c5'
down_revision = 'a48381bcbf1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
