"""Added date to Card

Revision ID: a48381bcbf1f
Revises: b59d0ccd3ef2
Create Date: 2021-10-14 01:07:01.171021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a48381bcbf1f'
down_revision = 'b59d0ccd3ef2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('create_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cards', 'create_date')
    # ### end Alembic commands ###
